# Generated by Django 4.1.4 on 2023-01-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='inside',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='post_time',
        ),
    ]
