# Generated by Django 4.1.4 on 2023-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_blog_post_inside_remove_blog_post_post_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home_page',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='isi',
            field=models.TextField(null=True),
        ),
    ]
