# Generated by Django 4.1.4 on 2023-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='github_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='twitter_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='webname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
