# Generated by Django 4.1.4 on 2023-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_blog_post_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.CharField(choices=[('article', 'article'), ('music', 'music')], max_length=10, null=True),
        ),
    ]
