# Generated by Django 4.1.4 on 2023-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_blog_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='download',
            field=models.TextField(blank=True),
        ),
    ]
