# Generated by Django 4.1.4 on 2023-01-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_blog_post_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='download',
            field=models.TextField(blank=True, null=True),
        ),
    ]
